live_config_reload = true
import = [
    "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 25
y = 20

[font]
size = 12.0

[font.bold]
family = "0xProto Nerd Font Propo"
style = "Heavy"

[font.bold_italic]
family = "0xProto Nerd Font Propo"
style = "Heavy Italic"

[font.italic]
family = "0xProto Nerd Font Propo"
style = "Medium Italic"

[font.normal]
family = "0xProto Nerd Font Propo"
style = "Medium"

